BaseURL = "http://baruch.lubinsky.co.za"
languageCode = "en-us"
title = "Baruch Lubinsky"
theme = "hyde"
Copyright = "Baruch Lubinsky"
PygmentsStyle = "friendly"
disqusShortname = "blcodingblog"

[author]
	name = "Baruch Lubinsky"

[permalinks]
	post = "/post/:year/:month/:filename/"

[taxonomies]
	tag = "tags"
	series = "series"

[Params]
	description = "My input to the positive feedback loop that is the internet."
	Copyright = "Baruch Lubinsky"
	github = "https://github.com/baruchlubinsky"
	disqus = "baruchlubinsky"

